---
:consumer_key: mJ5otbhPGNoDCgCL7j5g
:consumer_secret: M0XkT6GeBnjxdlWHcSGYX1JutMVS9D5ISlkqRfShg
:access_token: 3013867614-OmdoBZlquByViDfndbd7QQiSg65f2WK7aO9bStT
:access_token_secret: JjMNTl1bxZSQtC3BmlRhuKzTRrXtEVwldDCAihxhvh85j
